#!/bin/bash

#$ -cwd
#$ -o joblog.$JOB_ID
#$ -j y
#$ -l h_rt=10:00:00,h_data=20G  #,gpu,A100
#$ -pe shared 1
#$ -m a

# load the job environment:
. /u/local/Modules/default/init/modules.sh
module load anaconda3
conda activate base
conda activate tf_A100_clean

echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "

# --- DEFINE ARGUMENTS HERE ---
# 1. Path to your saved model
MODEL_PATH="CNN100x201/DANN_color_multiclass_sims_trained"

# 2. Path to the Source Data Directory (must contain Neu_sims.npy, HS_sims.npy, etc.)
SRC_DIR="/u/project/ngarud/Garud_lab/DANN/DANNcolor/ProcessingData/ProcessedMayaSims/"

# 3. Path to the Target Data Directory
TAR_DIR="/u/project/ngarud/Garud_lab/DANN/aDNA/ProcessingData/ProcessedDataALL/SortByRowFreq/"

# --- EXECUTE PYTHON SCRIPT ---
# We pass the variables defined above as arguments $1, $2, and $3
python PR_curves_multiclass_CNN.py "$MODEL_PATH" "$SRC_DIR" "$TAR_DIR"

echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `
echo " "