#!/bin/bash

#$ -cwd
# error = Merged with joblog
#$ -o joblog.$JOB_ID
#$ -j y
## Edit the line below as needed:
#$ -l h_rt=200:00:00,h_data=50G,highp   #,gpu,RTX2080Ti
## Modify the parallel environment
## and the number of cores as needed:
#$ -pe shared 1
# Notify when
#$ -m a

# load the job environment:
. /u/local/Modules/default/init/modules.sh
module load anaconda3
conda activate base
conda activate tf_A100_clean


# echo job info on joblog:
echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "


#run code
# "HS_sims.npy" [samples#] [SNPs#]
# There are 154 "good samples" according to Peter
# Try many different SNPs# values to see which works best:
# Attempt 1: [154] [201]; Attempt 2: [154] [250]; Attempt 3: [154] [300]
python processSLiMsims_ManagerScript.py "HS_sims.npy" 154 201


# echo job info on joblog:
echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `
echo " "